- hosts: schedd
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - name: qedit
    ansible.builtin.shell:
      cmd: condor_qedit -con 'jobuniverse==7&&jobstatus==5&&HoldReason=="ORACLEOFF (by user condor)"&&HoldReasonSubCode==20231212' HoldKillSig \"SIGUSR1\"
    register: shelloutput
  - ansible.builtin.debug: var=shelloutput.stdout_lines
  - name: release
    ansible.builtin.shell:
      cmd: condor_release -con 'jobuniverse==7&&jobstatus==5&&HoldReason=="ORACLEOFF (by user condor)"&&HoldReasonSubCode==20231212'
    register: shelloutput
  - ansible.builtin.debug: var=shelloutput.stdout_lines
